### ISSUE TITLE
Improve Ruby/Rails documentation in README

### ISSUE THREAD

**Issue by migurski** [codeforamerica/lexington-special-events#1]
The Readme document should link to docs in the [howto repository](https://github.com/codeforamerica/howto) for language & framework installation instructions, with some introductory text e.g. "Special Events is a Rails application, here’s how to get Ruby/Rails running on your environment [link to howto]"

**Comment by eeeschwartz** [comment]
Good call. Committed [here](https://github.com/codeforamerica/lexington-special-events/commit/65bb4654012946c46a3c21b36a0ee2ed758f0398).
